compiler: g++-6
dist: trusty
language: cpp
sudo: required

addons:
  apt:
    packages:
      - g++-6-multilib
    sources:
      - ubuntu-toolchain-r-test

env:
  global:
    - PREMAKE_DIR=$TRAVIS_BUILD_DIR/Premake
  matrix:
    - CONFIGURATION=Debug ARCHITECTURE=x86
    - CONFIGURATION=Debug ARCHITECTURE=x86_64
    - CONFIGURATION=Release ARCHITECTURE=x86
    - CONFIGURATION=Release ARCHITECTURE=x86_64

git:
  depth: 1

before_install:
  - sudo -E dpkg --add-architecture i386
  - sudo -E apt-get -yq update
  - sudo -E update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install linux-libc-dev:i386

before_script:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz
  - tar xzf premake-*-linux.tar.gz -C ${PREMAKE_DIR}

script:
  - cd ${PREMAKE_DIR}
  - chmod 755 ./GenerateGNUMakeProject.sh
  - ./GenerateGNUMakeProject.sh ${ARCHITECTURE}
  - cd Project
  - make config=${CONFIGURATION,,}