compiler: g++-7
dist: trusty
language: cpp

addons:
  apt:
    packages:
      - g++-7-multilib
      - libmariadbclient-dev:i386
      - linux-libc-dev:i386
    sources:
      - ubuntu-toolchain-r-test

env:
  global:
    - PREMAKE_DIR=$TRAVIS_BUILD_DIR/Premake
  matrix:
    - CONFIGURATION=Debug ARCHITECTURE=x86
    - CONFIGURATION=Debug ARCHITECTURE=x86_64
    - CONFIGURATION=Release ARCHITECTURE=x86
    - CONFIGURATION=Release ARCHITECTURE=x86_64

git:
  depth: 1

before_script:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-linux.tar.gz
  - tar xzf premake-*-linux.tar.gz -C ${PREMAKE_DIR}

script:
  - cd ${PREMAKE_DIR}
  - chmod 755 ./GenerateGNUMakeProject.sh
  - ./GenerateGNUMakeProject.sh ${ARCHITECTURE}
  - cd Project
  - make config=${CONFIGURATION,,} CXX=g++-7